version: 2
machine:
  timezone: Europe/Helsinki
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/anhpham1509/cd-pipeline-poc
    steps:
      - checkout
      - run:
          name: Setup bot user for git
          command: |
            git remote add pushback https://${GITHUB_TOKEN}@github.com/anhpham1509/cd-pipeline-poc.git
            git config --global user.name ${BOT_NAME}
            git config --global user.email ${BOT_EMAIL}
      - run:
          name: Install dep
          command: |
            DEP_VERSION=0.4.1
            curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
            chmod +x $GOPATH/bin/dep
      - restore_cache:
          keys:
            - deps-{{ arch }}-{{ checksum "Gopkg.lock" }}
      - run:
          name: make install
          command: |
            make install
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              if [[ $(git status --porcelain) ]]; then
                git add --all
                git commit -m "BOT: Make install"
              fi
            fi
      - save_cache:
          key: deps-{{ arch }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor
      - run: make setup
      - run:
          name: make format
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              make format
              if [[ $(git status --porcelain) ]]; then
                git add --all
                git commit -m "BOT: Format code"
              fi
            fi
      - run: make lint
      - run: make test
      - run:
          name: Upload coverage to codecov.io
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Push changes
          command: |
            if [[ $CIRCLE_BRANCH != "master" ]]; then
              if [[ $(git log origin/$CIRCLE_BRANCH..$CIRCLE_BRANCH) ]]; then
                echo "Pushing autobot fixes"
                git push --set-upstream pushback $CIRCLE_BRANCH
                exit 1
              fi
            fi
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build

  acceptance-testing:
    docker:
      - image: google/cloud-sdk:198.0.0
    steps:
      - run: make deploy

  deploy:
    docker:
      - image: google/cloud-sdk:198.0.0
    steps:
      - run: make deploy

workflows:
  version: 2
  cd-pipeline:
    jobs:
      - build
      - acceptance-testing:
          requires:
            - build
      - deploy:
          requires:
            - acceptance-testing
