apiVersion: v1
kind: Service
metadata:
  name: sap
  labels:
    app: sap
    tier: backend
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: sap
    tier: backend
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: sap
  labels:
    app: sap
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sap
      tier: backend
  template:
    metadata:
      annotations:
        description: Backend SAP
        version: $DOCKER_TAG
      labels:
        app: sap
        tier: backend
    spec:
      containers:
      - name: sap
        image: $DOCKER_REGISTRY/$PROJECT/sap:$DOCKER_TAG
        env:
        - name: PG_HOST
          value: $PG_HOST
        - name: PG_PORT
          value: $PG_PORT
        - name: PG_USER
          value: $PG_USER
        - name: PG_PASSWORD
          value: $PG_PASSWORD
        - name: PG_DATABASE
          value: $PG_DATABASE
        - name: PG_SSL_MODE
          value: $PG_SSL_MODE
        - name: PORT
          value: "3000"
        - name: GIN_MODE
          value: "release"
        ports:
        - name: http
          containerPort: 3000
